version: '3'

services:
  pets-and-paws-client:
    image: pets-and-paws-client
    container_name: pets-and-paws-client
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "8080:80"
    env_file:
      - .env.production
    environment:
      - VITE_MESSAGE=hello from docker broh ;)